

export const FETCH_PUBLIC_GISTS_USER_PENDING = "FETCH_PUBLIC_GISTS_USER_PENDING";
export const FETCH_PUBLIC_GISTS_USER_SUCCESS = "FETCH_PUBLIC_GISTS_USER_SUCCESS";
export const FETCH_PUBLIC_GISTS_USER_ERROR = "FETCH_PUBLIC_GISTS_USER_ERROR";

export const FETCH_GIST_DETAILS_PENDING = "FETCH_GIST_DETAILS_PENDING";
export const FETCH_GIST_DETAILS_SUCCESS = "FETCH_GIST_DETAILS_SUCCESS";
export const FETCH_GIST_DETAILS_ERROR = "FETCH_GIST_DETAILS_ERROR";




